# Generated by Django 3.0.5 on 2020-08-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200615_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follows',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
